import { config } from "./config.js";

// Same list as the original api.js — unrelated to the backend, so it's
// reproduced as-is rather than fetched from anywhere.
export const DELIVERY_SOURCES = Object.freeze([
  "reddit",
  "private",
  "paid",
  "free",
  "returning",
  "other"
]);

function apiUrl(path) {
  return `${config.apiBaseUrl}${path}`;
}

async function parseJsonSafely(response) {
  try {
    return await response.json();
  } catch {
    return null;
  }
}

async function apiFetch(path, options = {}) {
  const response = await fetch(apiUrl(path), {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers
    }
  });
  const result = await parseJsonSafely(response);
  if (!response.ok) {
    const message = result?.error || result?.detail || `Request failed with HTTP ${response.status}.`;
    throw new Error(message);
  }
  return result;
}

function toUnixSeconds(value) {
  if (typeof value === "number") return Math.floor(value);
  return Math.floor(new Date(value).getTime() / 1000);
}

/* =========================================================
   LIST DELIVERIES
========================================================= */

export async function listDeliveries() {
  return apiFetch("/admin/deliveries");
}

/* =========================================================
   CREATE DELIVERY

   Internally a three-step exchange with the Worker (init -> direct-to-R2
   upload -> finalize, see Phase 2 §8), but that's invisible to the
   caller: the signature and behaviour match the original Supabase-backed
   createDelivery(metadata, files, onProgress) exactly, including that
   metadata.id (pre-generated by dashboard.js via shared.js's
   deliveryId()) is honoured rather than overwritten.
========================================================= */

export async function createDelivery(metadata, files, onProgress) {
  const init = await apiFetch("/admin/uploads/init", {
    method: "POST",
    body: JSON.stringify({
      deliveryId: metadata.id,
      files: files.map((f) => ({ fileName: f.name, fileSize: f.size }))
    })
  });

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const upload = init.uploads[i];
    const putResponse = await fetch(upload.putUrl, {
      method: "PUT",
      body: file
    });
    if (!putResponse.ok) {
      throw new Error(`Upload failed for ${file.name} (HTTP ${putResponse.status}).`);
    }
    onProgress?.((i + 1) / files.length);
  }

  await apiFetch("/admin/uploads/finalize", {
    method: "POST",
    body: JSON.stringify({
      deliveryId: init.deliveryId,
      uploadIds: init.uploads.map((u) => u.uploadId),
      projectName: metadata.project_name ?? null,
      clientName: metadata.client_name ?? null,
      notes: metadata.notes ?? null,
      expiresAt: toUnixSeconds(metadata.expires_at),
      supportEnabled: metadata.support_enabled ?? true,
      isPhotoshopBattles: metadata.source_meta?.type === "photoshop_battles",
      source: metadata.source ?? null,
      sourceMeta: metadata.source_meta ?? null,
      redditSource: metadata.reddit_source ?? null
    })
  });
}

/* =========================================================
   UPDATE DELIVERY
========================================================= */

const UPDATE_FIELD_MAP = {
  project_name: "projectName",
  client_name: "clientName",
  notes: "notes",
  expires_at: "expiresAt",
  source: "source",
  source_meta: "sourceMeta",
  reddit_source: "redditSource"
};

export async function updateDelivery(deliveryId, updates = {}) {
  if (!deliveryId) throw new Error("updateDelivery: delivery ID is required.");
  if (!updates || typeof updates !== "object") {
    throw new Error("updateDelivery: updates must be an object.");
  }

  const payload = {};
  for (const [snakeKey, camelKey] of Object.entries(UPDATE_FIELD_MAP)) {
    if (Object.prototype.hasOwnProperty.call(updates, snakeKey)) {
      payload[camelKey] =
        snakeKey === "expires_at" && updates[snakeKey] != null
          ? toUnixSeconds(updates[snakeKey])
          : updates[snakeKey];
    }
  }

  if (Object.keys(payload).length === 0) {
    throw new Error("updateDelivery: no editable fields were supplied.");
  }

  await apiFetch(`/admin/deliveries/${encodeURIComponent(deliveryId)}`, {
    method: "PATCH",
    body: JSON.stringify(payload)
  });
}

/* =========================================================
   DELETE DELIVERY (physical files only — see Phase 3 §13/§5)
========================================================= */

export async function deleteDelivery(delivery) {
  await apiFetch(`/admin/deliveries/${encodeURIComponent(delivery.id)}/delete-files`, {
    method: "POST"
  });
}

/* =========================================================
   DUPLICATE DELIVERY
========================================================= */

export async function duplicateDelivery(delivery) {
  return apiFetch(`/admin/deliveries/${encodeURIComponent(delivery.id)}/duplicate`, {
    method: "POST"
  });
}

/* =========================================================
   PUBLIC DELIVERY
========================================================= */

export async function getPublicDelivery(id) {
  const response = await fetch(apiUrl(`/api/d/${encodeURIComponent(id)}`));
  if (response.status === 404) return null;
  const result = await parseJsonSafely(response);
  if (!response.ok) {
    throw new Error(result?.error || `Request failed with HTTP ${response.status}.`);
  }
  return result;
}

/* =========================================================
   ANALYTICS
========================================================= */

export async function recordView(id) {
  try {
    await apiFetch(`/api/d/${encodeURIComponent(id)}/view`, { method: "POST" });
    return true;
  } catch (error) {
    console.error("[Boztik Deliver] recordView failed:", error);
    return false;
  }
}

export async function recordDownload(id) {
  try {
    await apiFetch(`/api/d/${encodeURIComponent(id)}/download`, { method: "POST" });
    return true;
  } catch (error) {
    console.error("[Boztik Deliver] recordDownload failed:", error);
    return false;
  }
}

/* =========================================================
   SIGNED DOWNLOAD / PREVIEW

   file.delivery_id / file.file_path come straight from getPublicDelivery's
   delivery_files array — file_path holds this system's short fileId
   rather than a literal storage path (see types.ts's PublicDelivery doc
   comment on the Worker side for why that's safe).
========================================================= */

async function requestSignedUrl(file, intent) {
  if (!file?.file_path) {
    throw new Error("requestSignedUrl: file.file_path is missing — cannot request a signed URL for an unknown object.");
  }
  const deliveryId = file.delivery_id || file.deliveryId;
  if (!deliveryId) {
    throw new Error("requestSignedUrl: delivery ID is missing.");
  }

  const result = await apiFetch(
    `/api/d/${encodeURIComponent(deliveryId)}/files/${encodeURIComponent(file.file_path)}/access?intent=${intent}`,
    { method: "POST" }
  );
  return result.url;
}

export async function signedDownload(file) {
  return requestSignedUrl(file, "download");
}

export async function signedPreview(file) {
  return requestSignedUrl(file, "preview");
}

/* =========================================================
   REDDIT METADATA
   Best-effort only. Callers must treat any thrown error as
   "auto-fill unavailable" and fall back to manual entry — never
   block delivery creation on this.
========================================================= */

export async function fetchRedditMetadata(url) {
  const trimmedUrl = (url || "").trim();
  if (!trimmedUrl) {
    throw new Error("No Reddit URL supplied.");
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8000);

  let response;
  try {
    response = await fetch(apiUrl(`/api/reddit-metadata?url=${encodeURIComponent(trimmedUrl)}`), {
      signal: controller.signal
    });
  } catch (error) {
    const timedOut = error?.name === "AbortError";
    throw new Error(timedOut ? "Reddit took too long to respond." : "Could not reach the metadata service.");
  } finally {
    clearTimeout(timeout);
  }

  const result = await parseJsonSafely(response);
  if (!response.ok || !result?.title) {
    throw new Error(result?.message || "Could not read this Reddit thread's title.");
  }

  return {
    title: result.title,
    subreddit: result.subreddit || null,
    author: result.author || null,
    canonicalUrl: result.canonicalUrl || result.redditUrl || trimmedUrl,
    redditUrl: result.redditUrl || trimmedUrl
  };
}
